### ISSUE TITLE
Add support for OpenSSL sockets

### ISSUE THREAD

**Issue by rfestag** [socketry/async-io#2]
I'm looking into porting over my old SSL code, and I'm not sure where to begin. Do I need to create a new Async::IO::Address for ssl (that seems weird because it is TCP)? How do I initialize the SSLServer (I need to pass it a TCPServer and an SSLContext, then call  my IO operations on the SSLServer).

Would it be correct to simply wrap OpenSSL::SSL::Server (as I did before)?

**Comment by ioquatix** [comment]
All good questions. Here is a rough outline of how I think it should work.

So, yes, the key point is that an `Address` is supposed to be a very high level construct to assist with the construction of sockets, and it allows servers to be super simple - the person using the library essentially provides a list of addresses, and your server binds to them, and implements the correct logic.

SSL is essentially a stream socket. It makes sense to be able to write Address.ssl(address, port, ssl_context: ...)

When the server calls `address.bind`, it should make the correct socket. It probably makes sense to instantiate a TCP socket and pass that to the SSL socket wrapper. This way, when the SSL socket call's accept on the underlying socket, it gets non-blocking behaviour.

I'm not really sure how this all fits together but if you supply a PR with some specs that would be awesome, and we can go from there. Ideally, you shouldn't need to modify the Address class too much. Ideally, Address remains as light weight as possible.

The reason why `Address` exists and does as much multiplexing as it does, is because of the kinds of requests I had in the past - some people wanted to pass in existing bound sockets, and it's quite different to handle that as compared to just an ip/port for example. The primary difference is lifetime of the socket - basically who is responsible for calling close. I didn't want every server implementation to have to handle those issues, so the Address class is an abstraction that simplifies servers. Ideally, the server doesn't need to know anything about SSL sockets, just that it's given a stream (or datagram) socket.

Hopefully this all makes sense.

I think the Address class is a prime candidate for simplification - perhaps a sub-class to handle different behaviours.

**Comment by ioquatix** [comment]
I recall you were interested in HTTP servers using async - here is what I've done so far https://github.com/socketry/falcon

**Comment by rfestag** [comment]
Sorry for the late reply, I haven't had as much time lately to poke around. I came the to the same conclusion regarding getting the initial TCP connection working. Part of where I'm confused at this point is that I want TCP and SSL accept methods to be nonblocking. As I understand, I would do something like this:

1) sock = tcp_server.accept_nonblock
2) ssl_sock = SSLSocket.new(sock, context)
3) connection = ssl_sock.accept_nonblock
4) read_nonblock/write_nonblock on the connection

I have an example that seems to be working using nio4r directly. I'm not sure if it is correct (it seems slower than I would have expected, but there could be other issues getting in the way). I'll see if I can get a PR together with just some specs, and see where that goes.

**Comment by tarcieri** [comment]
@rfestag yes, however make sure when calling `SSLSocket#accept_nonblock` you handle both read and write readiness requests. The TLS handshake is at best 1-RTT (until TLS 1.3 adds 0-RTT, although earlier versions of TLS are more typically 2-RTT in practice) so you may need to wait to read or write to complete the handshake.

See the relevant code in Socketry:

https://github.com/socketry/socketry/blob/master/lib/socketry/ssl/socket.rb

**Comment by ioquatix** [comment]
Still looking forward to this if you have time!

**Comment by ioquatix** [comment]
@tarcieri We handle the handshake transparently in a task before the user code is invoked, so a slow handshake won't DOS a server by default.

**Comment by tarcieri** [comment]
Sounds good

**Comment by ioquatix** [comment]
It was interesting to see how you worked through this in socketry. It's also interesting because I did have to make a slight deviation in the way the accept API works. The handshake process makes things a bit more complex.

The ssl specs in socketry were also a super useful starting point and I used those exact same certs in `async-io`.

When I implemented the SSL specs for `falcon` I used OpenSSL to generate in-memory certs rather than writing files to disk, I thought you might find it equally interesting:

https://github.com/socketry/falcon/blob/11df710375e0fb868fc20bbdc569804ce6a8ccd5/spec/falcon/ssl_server_spec.rb#L30-L57

**Comment by tarcieri** [comment]
I've gone back and forth on "simple script to generate pre-generated certs" versus "dynamically generate certs on the fly".

http.rb kind of went off the deep end on dynamically generating certs:

https://github.com/httprb/http/blob/master/spec/support/ssl_helper.rb

Glad the rest of the Socketry code/specs were helpful

**Comment by ioquatix** [comment]
Dude, the socketry code base is a beautiful work of art. That doesn't mean it's how I'd design it, but I appreciate it for what it is and the logic behind it, and when I was reading it, it was really talking to me in a way that few code bases do. Most code just sounds like garbage, but not `socketry`.

I can certainly understand some of your frustrations with the Ruby IO classes too. Socketry sort of takes it to the extreme in terms of design - like, how you've allowed injection of socket classes everywhere.

Here is what I ended up with, https://github.com/socketry/async-rspec/blob/master/lib/async/rspec/ssl.rb as it's shared across all projects that want to test SSL.

**Comment by ioquatix** [comment]
Also, I appreciate your work on `hostname=` for hostname verification. I saw the conversation surrounding that and I can imagine it was a bit frustrating given that it seems like a fairly fundamental feature but that people don't really take it seriously.
